name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cloudnativeacr01.azurecr.io/cloudnativeaction:latest
     
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: cloudnativeacr01
        # Container registry password
        password: ${{ secrets.ACR_CREDENTIALS }} 
        # Container registry server url
        login-server: cloudnativeacr01.azurecr.io
        
    - name: Push Image  
      run: docker push cloudnativeacr01.azurecr.io/cloudnativeaction:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job   
    steps:
    - uses: actions/checkout@v2
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1.1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        # Resource Group Name
        resource-group: CloudNativeRG
        # AKS Cluster Name
        cluster-name: sidaks01
        
    - name: Kubernetes Deployment
      run: kubectl apply -f deployment.yaml
    - name: Service Deployment
      run: kubectl apply -f service.yaml
    
  
    
